name: 🚀 Auto Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect and Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "✅ Connected to EC2"
            cd /home/ec2-user/patientapp_backend
            git pull origin main
            npm install
            pm2 restart patient-backend --update-env
            echo "✅ Deployment finished"
